### ISSUE TITLE
Research DB Technologies

### ISSUE THREAD

**Issue by fritogotlayed** [MadDonkeySoftware/RAG-Report#1]
Research the various DB technologies that we could use. This should include both embedded and traditional DBs. 

EXPECTED OUTCOME

**Comment by jbarganier** [comment]
here are my [rambling notes](https://github.com/MadDonkeySoftware/RAG-Report/files/27717/python-database_notes.txt) regarding postgresql and mysql in python from last week's meeting. I didn't look into sqlite at the time. All three are supported in Python 3 and [Sqlalchemy](http://www.sqlalchemy.org/)

**Comment by jbarganier** [comment]
oops. too much coffee man clicked the wrong button

**Comment by fritogotlayed** [comment]
lol. Nice one :smile:

**Comment by fritogotlayed** [comment]
@jbarganier I'm closing this as I feel we have completed the research we need for now. We can create a new story specific to a DB technology we want to use or switch to when we get to that point.
