### ISSUE TITLE
Research and prototype a Unit Testing and mocking example

### ISSUE THREAD

**Issue by fritogotlayed** [MadDonkeySoftware/RAG-Report#2]
Research and prototype a Unit Testing and mocking example.

EXPECTED OUTCOME
A prototype example of a unit test using mock objects for the piece of code under test. This should be demo'd to the rest of the team.

**Comment by naitp** [comment]
super pre-alpha proto-prototype testing things have happened.

**Comment by fritogotlayed** [comment]
@naitp Lol. I agree. I would close this issue but you were going to research how the mocks were mapped to the method parameters so I'll leave it open for now :smile:

**Comment by naitp** [comment]
Per Frito, http://www.voidspace.org.uk/python/mock/patch.html?highlight=stack#nesting-patch-decorators shows how the mocks are mapped to the method parameters. He has also added tests/siteroot/test_controller.py (without decorators).

**Comment by fritogotlayed** [comment]
Closing since test example was good with team at last meeting.
