### ISSUE TITLE
Registering a new user account with a non-unique nickname results in failure

### ISSUE THREAD

**Issue by jbarganier** [MadDonkeySoftware/RAG-Report#24]
Attempting to register a new user account with a nickname that matches an existing record in the database will cause a unique constraint failure to occur on the users_user.name column. 

? can we just remove the unique constraint on the name field?  It looks like the email address is what really needs to be unique.

**Comment by fritogotlayed** [comment]
@jbarganier That is fine with me.

**Comment by jbarganier** [comment]
forgot to assign this to me

**Comment by jbarganier** [comment]
ready for review....
